import esbuild from "esbuild";
import { builtinModules } from "node:module";
import process from "process";

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const nodeBuiltins = builtinModules.filter((m) => !m.startsWith("node:"));
const external = ["obsidian", "electron", ...nodeBuiltins];

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/core/main.ts"],
    bundle: true,
    external,
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
